/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.rita.se;

import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class functions extends javax.swing.JFrame {

   
    
    private final String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=rita se; user=sa;password=12345"; 
    
    
    
    public functions() {
        initComponents();
        
        
        
        
              try{ 

Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");   

} 

catch(ClassNotFoundException ex){ 

JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!"); 

} 
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        count_btn = new javax.swing.JButton();
        maximum_btn = new javax.swing.JButton();
        minimum_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        count_btn.setText("count");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });

        maximum_btn.setText("maximum");

        minimum_btn.setText("minimum");
        minimum_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimum_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minimum_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(count_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maximum_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(count_btn)
                .addGap(50, 50, 50)
                .addComponent(maximum_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(minimum_btn)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
       
        
        
        
        Connection conn=null;
        Statement stmt= null;
        ResultSet result = null;
        
        
        try{
        
        
          conn = DriverManager.getConnection(url);
            stmt = conn.createStatement();
            String query ="SELECT COUNT (*) as users_id FROM users ";
            
            result = stmt.executeQuery(query);

            int affectRows=  stmt.executeUpdate(query);

            if(result.next())
            {

                int count = result.getInt("users_id");
                JOptionPane.showMessageDialog(this, "users count = " +count);

            }
            else
            {

                JOptionPane.showMessageDialog(this, "No count");
            }
        
        
        
        
        
        
        }
        catch(Exception ex)
        {
        
        JOptionPane.showMessageDialog(this, ex.getMessage());
        
        }
        
         {

            if(conn != null) {try{conn.close();} catch (Exception ec){}}

            if(stmt != null) {try{stmt.close();} catch (Exception ec){}}
              if(result != null) {try{result.close();} catch (Exception ec){}}
            
        }

        
        
        
        
        
        
        
    }//GEN-LAST:event_count_btnActionPerformed

    private void minimum_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimum_btnActionPerformed




 Connection conn=null;
        Statement stmt= null;
        ResultSet result = null;
        
        
        try{
        
        
          conn = DriverManager.getConnection(url);
            stmt = conn.createStatement();
            String query ="SELECT min (age)  FROM users  ";
            
            result = stmt.executeQuery(query);

            int affectRows=  stmt.executeUpdate(query);

            if(result.next())
            {

                int min = result.getInt("age");
                JOptionPane.showMessageDialog(this, "max age = " +min);

            }
            else
            {

               
            }
         
        
        }
        catch(Exception ex)
        {
        
        JOptionPane.showMessageDialog(this, ex.getMessage());
        
        }
        
         {

            if(conn != null) {try{conn.close();} catch (Exception ec){}}

            if(stmt != null) {try{stmt.close();} catch (Exception ec){}}
              if(result != null) {try{result.close();} catch (Exception ec){}}
            
        }
















        // TODO add your handling code here:
    }//GEN-LAST:event_minimum_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new functions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton count_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maximum_btn;
    private javax.swing.JButton minimum_btn;
    // End of variables declaration//GEN-END:variables
}
